baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = "MakiNaruto's Blog"


copyright = ""
refLinksErrorLevel = "warning"
[pagination]
  pagerSize = 10

enableInlineShortcodes = true
enableEmoji = true
# 防止在使用Instagram 快捷代码时由于不推荐使用 Instagram API而导致构建失败。
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

# 防止使用模板 _internal/opengraph.html 时生成失败
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark]
[markup.goldmark.extensions]
    [markup.goldmark.extensions.passthrough]
    enable = true
    [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['\$', '\$']]

[markup.goldmark.renderer]
unsafe = true


[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50
[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/MakiNaruto/"
weight = 100


[params]
math = true
author = "MakiNaruto"
description = "Le vent se lève, il faut tenter de vivre"
keywords = "blog, developer, personal"
img_home = "img/Program-is-an-art-form.jpg"
img_404 = "img/404-bg.jpg"

useFaviconGenerator = true

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = true
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/MakiNaruto.jpg"
bio = "纵有疾风起, 人生不言弃"

[params.social]
zhihu = "makinaruto"
github = "MakiNaruto"


# See https://giscus.app/
[params.giscus]
enable = true
repo = "MakiNaruto/MakiNaruto.github.io"
repo_id = "R_kgDOLdUvlw"
category = "General"
category_id = "DIC_kwDOLdUvl84Cd1hR"
input_position = "top"
theme = "light_tritanopia"

